Admin register plan by playlist
TreinaDev/stream-alpha pull request #114
Opened 2021-11-26 20:11 UTC by angelasoler

- administrado pode criar planos inclindo varias playlist
- associação has_many para has_many, entre plan e playlist, com tabela intermediaria, content_playlist

2021-11-29 16:58 UTC, joaorsalmeida commented on app/views/plans/_form.html.erb
> +    <%= f.collection_select :playlist_ids, @playlists, :id ,:name, { prompt: true }, { multiple: true } %>
Eu prefiro `check_box` mas ok. Acho a usabilidade desse cara muito ruim :(

2021-11-29 16:59 UTC, joaorsalmeida requested changes

2021-11-29 16:59 UTC, joaorsalmeida commented on spec/system/admin_register_plan_spec.rb
> +      playlist1 = create(:playlist)
Mudem esse teste para ter mais uma playlist, não selecionem ela e ao fim garantam que essa nova playlist não foi vinculada.

2021-11-30 18:20 UTC, LeDragoX commented
Quando for puxarem o `Rubocop` pra resolver os conflitos, tira a linha `"- config/routes.rb"`.
Só fui perceber depois que foi mergeado #117

2021-11-30 20:11 UTC, angelasoler commented on app/views/plans/_form.html.erb
> +    <%= f.collection_select :playlist_ids, @playlists, :id ,:name, { prompt: true }, { multiple: true } %>
Foi feito desta forma pois foi combinado com a equipe que seria usado o tailwind para o front-end o que mehoraria a usabilidades. Porem, caso não for usada essa gem no projeto re-fatoraremos antes de sexta para check_box como vc nos recomenda :)

2021-11-30 20:30 UTC, angelasoler commented on spec/system/admin_register_plan_spec.rb
> +      playlist1 = create(:playlist)
Feito

2021-12-01 15:09 UTC, OtavioLins approved these changes

2021-12-01 15:10 UTC, OtavioLins approved these changes

2021-12-01 15:45 UTC, joaorsalmeida approved these changes

2021-12-01 18:41 UTC, merged