Criar conta e perfil de Streamer
TreinaDev/stream-alpha pull request #19
Opened 2021-11-17 01:55 UTC by LeDragoX

Issue #14
- Perfil deve ser único
- Traduzido views do Devise Streamer
- Botão Meu perfil pode ser encontrado na barra de navegação
- Feitas factories e seeds para Streamer e Perfil de Streamer
- Título temporário para a Home page
- Depois de logar como streamer o perfil é obrigatório, outras telas ainda estão visiveis

Co-authored-by: FernandoInkaPuri <FernandoInkaPuri@users.noreply.github.com>

2021-11-17 12:57 UTC, joaorsalmeida commented on app/controllers/streamer_profiles_controller.rb
> +  def is_owner?
Eu acho que esse método vai ser útil, poderia ir pro modelo ao invés da View.

2021-11-17 12:59 UTC, joaorsalmeida commented on spec/system/streamer_register_profile_spec.rb
> +    it 'and fill profile' do
Não conseguem adicionar ao menos mais 1 cenário aqui? Acho que só falto isso pra ficar 💯

2021-11-17 13:00 UTC, joaorsalmeida requested changes
Gostei muito do PR 🏎️ 

Mas preciso muito que vcs criem ao menos mais 1 cenário para os testes de formulário, pode ser?

2021-11-17 13:49 UTC, LeDragoX commented on spec/system/streamer_register_profile_spec.rb
> +    it 'and fill profile' do
@FernandoInkaPuri faz essa parte aqui, tô sem tempo hj

2021-11-17 17:05 UTC, FernandoInkaPuri commented on spec/system/streamer_register_profile_spec.rb
> +    it 'and fill profile' do
Sim

2021-11-18 14:35 UTC, joaorsalmeida approved these changes
Bora ⏩

2021-11-18 14:39 UTC, merged