Admin aprova video
TreinaDev/stream-alpha pull request #60
Opened 2021-11-19 23:27 UTC by DaniloJNS

- Fluxo de aceitar e recusar videos por um administrador
- Testes verificando se o video ja foi analisado
- Teste se listagem de videos mostra apenas video que ainda não foram analisados
- Rotas protegidas

2021-11-22 22:09 UTC, joaorsalmeida requested changes
Tem varios trechos e arquivos que são sujeira de outro merge. Podem revisar isso por favor?

2021-11-22 22:09 UTC, joaorsalmeida commented on app/controllers/admins_controller.rb.orig
> +class AdminsController < ApplicationController
Me parece que esse arquivo 'escapou'

2021-11-22 22:09 UTC, joaorsalmeida commented on app/views/admins/admin_area.html.erb
> +<<<<<<< HEAD
Escapou aqui também...

2021-11-22 22:09 UTC, joaorsalmeida commented on app/models/video.rb
> +  scope :all_in_analysis, -> { where(status: 'pending') }
Legal mas vocês sabem que o `enum` gera escopo automaticamente? No caso dessa classe o `enum` gera automaticamente os seguintes scopes: `Video.pending`, `Video.approved` e `Video.refused`

2021-11-22 22:09 UTC, joaorsalmeida commented on app/models/video.rb
> +  scope :all_in_analysis, -> { where(status: 'pending') }
PS: não precisa modificar se acharem que esta mais expressivo o método de vocês, quis mais apontar essa possibilidade via Enum

2021-11-22 22:09 UTC, joaorsalmeida commented on app/views/admins/admin_area.html.erb.orig
> +<<<<<<< HEAD
Esse arquivo também tem vários trechos com problemas de merge

2021-11-22 22:09 UTC, joaorsalmeida commented on config/routes.rb.orig
> +Rails.application.routes.draw do
ARquivo que talvez possamos apagar.

2021-11-22 22:09 UTC, joaorsalmeida commented on db/schema.rb.orig
> +# This file is auto-generated from the current state of the database. Instead
Apagar?

2021-11-23 04:11 UTC, angelasoler commented
- Problemas de merge corregidos
- Typo erros em spec de _game_category_ e view _admin_area_: Troquei _creation_date_ por _created_at_

2021-11-23 19:23 UTC, joaorsalmeida approved these changes
Vi que fizeram os ajustes, boa! 🏁

2021-11-23 20:25 UTC, merged