Administrador cria planos de assinatura
TreinaDev/stream-alpha pull request #84
Opened 2021-11-22 02:11 UTC by FernandoInkaPuri

- Administrador cria planos de assinatura, apenas com streamers vinculados ao plano.
- Administrador vê todos os planos cadastrados.

2021-11-22 22:26 UTC, joaorsalmeida requested changes
Fiz alguns comentários que recomendo a revisão e ajustes.

2021-11-22 22:26 UTC, joaorsalmeida commented on app/models/plan.rb
> +    has_many :streamer, through: :content_streamers
No singular? Ficou estranho na hora que vi o uso no Controller.

2021-11-22 22:26 UTC, joaorsalmeida commented on app/views/plans/new.html.erb
> +    <%@video_plan.errors.full_messages_for(:name).each do |message|%>
Pesquise depois como criar um `helper`. Me parece um caso clássico de View Helper esse código ;)

2021-11-22 22:26 UTC, joaorsalmeida commented on spec/system/admin_register_plan_spec.rb
> +describe 'Admin' do
Bora add cenários de não admins tentando acessar esse formulário?

2021-11-22 22:26 UTC, joaorsalmeida commented on spec/system/admin_register_plan_spec.rb
> +      click_on 'Entrar como Administrador'
Bora usar `login_as` aqui? Vai economizar um tempo considerável da execução dos testes.

2021-11-22 22:26 UTC, joaorsalmeida commented on spec/models/plan_spec.rb
> +RSpec.describe Plan, type: :model do
Nem um `shoulda_matchers` por aqui? 😢

2021-11-23 18:01 UTC, joaorsalmeida commented
Esse já foi atualizado né? Nao esquecam de marcar o `Resolve conversation` ;)

2021-11-23 18:03 UTC, joaorsalmeida requested changes
Encontrei mais um ponto que vale a pena ajustar.

2021-11-23 18:03 UTC, joaorsalmeida commented on app/views/plans/_form.html.erb
> +    <%= f.collection_select :streamer_ids, Streamer.where(profile_status:10), :id ,:email, { prompt: true }, { multiple: true } %>
Poderíamos levar essa query para o controller. E poderíamos usar altgo mais expressivo do que `10`. Viram que o `enum` cria métodos de `scope` automaticamente?

2021-11-23 18:53 UTC, joaorsalmeida reviewed
Depois me contem se vamos fazer os ajustes comentados aqui ou se vamos levar para o backlog.

2021-11-23 18:53 UTC, joaorsalmeida commented on spec/factories/content_streamers.rb
> +    plan
Esses `models` focados em associações muitos para muitos não costumam ter factories com os atributos pré-definidos. Podem ficar vazios para evitar criar dados incorretos nos testes e vamos sempre definir os dados durante o teste.

2021-11-24 08:03 UTC, FernandoInkaPuri commented on app/views/plans/_form.html.erb
> +    <%= f.collection_select :streamer_ids, Streamer.where(profile_status:10), :id ,:email, { prompt: true }, { multiple: true } %>
João realizei os ajustes de tudo que foi comentado, vou pedir para o pessoal dar uma olhada pela manhã.

2021-11-24 15:26 UTC, joaorsalmeida approved these changes

2021-11-24 16:53 UTC, LeDragoX commented on app/helpers/errors_helper.rb
> +  def error_plan(object, field)
Acho que renomear para **field_errors** ficaria mais interessante, já que isso envolve todos os forms.

2021-11-24 16:54 UTC, LeDragoX commented
Eu só tô comentando pq o @FernandoInkaPuri pediu pra eu olhar, e eu ajudei ele em algumas partes em um dia.
Pra ir guiando.

2021-11-24 17:02 UTC, LeDragoX commented on app/views/plans/_form.html.erb
> +    <% error_plan(@video_plan, :name).each do |message|%>
Vc consegue só me dizer se o erro tá aparecendo só uma vez, e não duplicado?
Não deve precisar nem alterar nada se já estiver aparecendo 1 vez.
Exemplo:
```
Nome: [                    ]
Nome não pode ficar em branco.
Nome não pode ficar em branco.
```

2021-11-24 17:24 UTC, FernandoInkaPuri commented on app/views/plans/_form.html.erb
> +    <% error_plan(@video_plan, :name).each do |message|%>
Tá aparecendo uma vez só

2021-11-24 19:50 UTC, merged