Criar Playlist
TreinaDev/stream-alpha pull request #88
Opened 2021-11-23 23:48 UTC by LeDragoX

- Cria várias playlists
- Adiciona foto da capa da playlist
- Adicionar bloqueio para usuários não autenticados em todas as rotas
- O admin pode criar playlists
- Refatorar método owner de client/streamer profiles
- Refatorar mensagens de erros para I18n

Resolve #58 

Co-authored-by: Danilo Nascimento <DaniloJNS@users.noreply.github.com>

2021-11-25 17:34 UTC, LeDragoX commented
Essa PR vai andar quando
- #103 for mergeada

2021-11-26 12:51 UTC, joaorsalmeida requested changes
Nos testes falta garantir que um vídeo não marcado não é vinculado à playlist. Esse tipo de teste é o mesmo tratamento que fazemos naqueles casos de buscas/filtros, lembram-se? Temos que garantir que os vídeos não vinculados via formulário realmente não são vinculados no código.

2021-11-26 12:51 UTC, joaorsalmeida commented on spec/system/admin_playlist_spec.rb
> +      video2 = create(:video, :approved, name: 'jogando fifa na master league')
Para ficar 100%, esse teste deveria ter um vídeo que não é selecionado e nas expectativas vocês confirma que o vídeo não aparece/não foi vinculado à playlist. Podem adicionar esse cenário (ou atualizar este aqui) por favor?

2021-11-26 15:55 UTC, joaorsalmeida approved these changes

2021-11-26 15:59 UTC, merged